### ISSUE TITLE
【必看】PostCSS-Bem 语法简洁教学

### ISSUE THREAD

**Issue by liwens** [tap-ui/course-vue-tap-ui#2]
开发组件库，我们选择了`PostCSS`作为CSS开发方案，`PostCSS`本身只是一个平台，他的核心就是插件，
 `PostCSS-salad`是一套插件集成方案，集成了常用的postcss插件，包括使用率非常高的`autoprefixer`CSS属性自动加前缀的插件。  具体插件可以查看[postcss-salad仓库](https://www.npmjs.com/package/postcss-salad)拉到底部，以及[文档](http://elemefe.github.io/postcss-salad/)。
## `PostCSS-Bem`
  `PostCSS-salad`使用了`PostCSS-Bem` 插件， 这是一种class命名风格的插件，网上的其他文档说话弯弯绕，我这里简单的介绍一下。
PostCSS-Bem 分为2种模式，默认为 `Suit模式` 。还有一个`Bem 模式`。 在`Bem模式`下没有`@utility`和`@when`语法。所以我们直接用默认的 `Suit模式`  ,写法类似sass，less等预处理的嵌套形式。优点是阅读更清晰。
### `@descendant`
使用`@descendant `编译生成类名时，会生成一个 破折号 `-` 来连接类名.

### `@modifier`
和`@descendant` 类似，不同的是`@modifier`生成两个扩折号 `--`连接类名<br>

### `@component `
`@component`中相对于一个块了，比如我要开发一个按钮组件，就用`Button` 作为块名<br>
来看下面代码，结合 上面提到的`@descendant`，`@modifier`，`@component `来一个综合的理解。
```CSS
@component button {
    border: 1px solid yellow;

    /* 尺寸 */
    @descendant small {
       font-size: 12px
    }

    /* 主题 */
    @modifier default {
       color: #eee
    }
}
```
编译生成
```CSS
.button {
 border: 1px solid yellow;
}

/* 尺寸 */
.button--small {
 font-size: 12px
}

/* 主题 */
.button-default {
 color: #eee
}
```

### @component-namespace
组件可以在命名前加一个这样的命名空间，来防止类名冲突，例如我们ui组件库叫`vue-tap-ui`, 然后我们使用`@component-namespace` 来添加命名空间。我们修改一下上面的示例代码
```CSS
  @component-namespace tap{
    @component Button {
      border:1px solid yellow;

      /* 尺寸 */
      @descendant small {
        font-size: 12px
      }

      /* 主题 */
      @modifier default {
        color: #eee
      }
    }
  }
```
编译生成
```CSS
.tap-button {
 border: 1px solid yellow;
}

/* 尺寸 */
.tap-button-small {
 font-size: 12px
}

/* 主题 */
.tap-button--default {
 color: #eee
}
```
可以看到在class最前面，都添加了`tap-`前缀。而`tap-button`,可以作为按钮的公共样式

### `@when`
当然还有一个`@when`， 来表示状态，会给类名添加`is-`前缀，`is`顾名思义，表示是否的意思。比如按钮组件是否 禁用`disabled`, 是否启用扁平风格 `plain` 。来看继续补充按钮的示例代码
```CSS
@component-namespace tap{
  @component Button {
    border:1px solid yellow;
    /* 主题 */
    @modifier default {
      color: #eee;

      @when plain {
        color: #fff
      }
    }

    /* 禁用 */
    @when disable {
      opacity: .4;
    }
  }
}
```
编译生成
```CSS
.tap-button {
  border: 1px solid yellow;
}

/* 主题 */
.tap-button-default {
  color: #eee
}
.tap-button-default.is-plain {
  color: #fff
}

/* 禁用 */
.tap-button.is-disable {
  opacity: .4;
}
```
### `@Utility`
还有一个`@Utility`，Utility 顾名思义，共用的工具。 会在类名前加`u-`前缀。 比如清除浮动
```CSS
 @Utility clearFix{...}
```
编译生成
```CSS
u-clearFix{...}
```

我们都介绍了什么情况下使用什么状态。 至于何时用`@modifier`，和 `@descendant`。 我的理解是<br>`descendant` 顾名思义 子节点， 比如一个搜索表单可能包括标题、文本框和提交按钮等元素，这些就用`descendent` <br>
`modifier` 顾名思义 调节器。表示 改变的描述，或者是状态改变。 比如一个按钮,有不同的主题，尺寸。不同的状态就用`modifier`
